services:
  whatsapp-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-extractor:latest
    container_name: whatsapp-extractor
    volumes:
      - ./pipeline/process/:/data/input:rw
      - ./pipeline/cache/whatsapp/:/data/cache:rw
      - ./pipeline/output/:/data/output:rw
    environment:
      - LOG_LEVEL=INFO
      - LOG_LEVEL_MONITOR=INFO
      - MONITOR_LOCK_FILENAME=Lock.lck
      - OUTPUT_STYLE=formatted_txt
      - CONVERSATION_TYPES=call_logs,chats,contacts