services:
  whatsapp-backup-chat-viewer:
    build: .
    image: whatsapp-backup-chat-viewer:latest
    volumes:
      - ./whatsapp_backup:/app/whatsapp_backup
      - ./output:/app/output
    deploy:
      replicas: 3