services:
  whatsapp-backup-chat-viewer:
    build: .
    image: whatsapp-backup-chat-viewer:latest
    ports:
      - "5000" # expose app port to nginx only
      # - "5000:5000" # for app port open to host
    volumes:
      - ./whatsapp_backup:/app/whatsapp_backup
      - ./output:/app/output
    deploy:
      replicas: 3
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./docker_scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - whatsapp-backup-chat-viewer