services:
  whatsapp-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-extractor:latest
    container_name: whatsapp-extractor
    volumes:
      - ./pipeline/process/:/data/input:ro
      - ./pipeline/cache/whatsapp/:/data/cache:rw
      - ./pipeline/output/communication/whatsapp/:/data/output:rw
    environment:
      - LOG_LEVEL=INFO
      - LOG_LEVEL_MONITOR=INFO
      - MONITOR_FILTER_PATTERN_FILE='*/database/whatsapp/*/*/*'